[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blink_take_2 = "45vxfU6DwN8eSJoYwU7qRoawKLEJBgFAbJGEjJyhosWz"

[programs.devnet]
blink_take_2 = "45vxfU6DwN8eSJoYwU7qRoawKLEJBgFAbJGEjJyhosWz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mukesh/.config/solana/id.json"

[scripts]
test = "pnpm test"
