[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blink_take_2 = "6kFaTqPvBH631tcQtQMfAYbpwxRe3e1bUrpy6Wo2aQyj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/akshatsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
